version: "3"

services:

    nginx:
        image: nginx:latest
        restart: always
        depends_on:
            - php
            - db
        networks:
            - backend
            - frontend
        ports:
            - "80:80"
        volumes: &app
            - ../:/var/www/html:delegated
            - ./nginx.conf:/etc/nginx/nginx.conf
        container_name: "web_taxi"

    php:
        build:
            context: './php'
        networks:
            - backend
        volumes: *app
        container_name: "php_taxi"

    db:
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        networks:
            - backend
        environment:
            MYSQL_ROOT_PASSWORD: linux
            MYSQL_DATABASE: dev
        container_name: "db_taxi"

networks:
    backend:
    frontend:
